#!/usr/bin/env bash
set -euo pipefail

REPO_URL="$(git config --get remote.origin.url)"
[ -d gh-pages ] || git clone -q --branch gh-pages "$REPO_URL" gh-pages
cd gh-pages

html_escape() {
  sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}

# Reject anything that isn't a plain PEP 503-style name (defense against
# unexpected upstream HTML being interpolated into shell or filesystem paths).
is_safe_name() {
  case "$1" in
    ""|.|..|*/*|*..*) return 1 ;;
  esac
  LC_ALL=C printf '%s' "$1" | grep -Eq '^[A-Za-z0-9._+-]+$'
}

checkCount() {
  local content="$1"
  local count="$2"
  local minimum="$3"

  if (( count < minimum )); then
    echo "!!! failing because low packages count for $content: $count (probably intermittent download failure)"
    exit 1
  fi
}

# update a PyPI index from PyTorch = https://download.pytorch.org/$d with d=whl or whl/<compute platform>
# this copies the content (main url + follows links to projects) and does 2 updates:
# 1. copies the content in a "simple/" sub-directory to match the convention from PEP 503 simple (that allows other APIs in parallel)
# 2. updates the links to binary packages by adding "https://download.pytorch.org" prefix to PyTorch-provided "/whl/*" path to link back to PyTorch binaries in their home location
updateIndex() {
  local d="$1"

  mkdir -p "$d/simple"
  local dir
  dir="$(pwd)"
  cd "$d/simple"

  # projects list
  curl -sf "https://download.pytorch.org/$d/" | grep -v 'TIMESTAMP 1' > index.html
  local count
  count="$(cut -d '>' -f 2 index.html | cut -d '<' -f 1 | grep -cve '^\s*$' || true)"

  echo "https://download.pytorch.org/$d/ => $d/simple/"
  checkCount "$d" "$count" 40

  # copy also content of each project
  local i=0
  local p
  while IFS= read -r p; do
    [ -z "$p" ] && continue
    if ! is_safe_name "$p"; then
      echo "skipping unsafe name: $p" >&2
      continue
    fi
    mkdir -p "$p"
    i=$((i+1))
    (
      cd "$p"
      curl -sf "https://download.pytorch.org/$d/$p/" \
        | sed -e 's_href="/whl_href="https://download.pytorch.org/whl_' \
        | grep -v 'TIMESTAMP 1' \
        > index.html
      pcount="$(grep -c 'https://download.pytorch.org/whl/' index.html || true)"
      printf "%5d / %s                   %s/%s/ => %s/simple/%s/ %s\n" "$i" "$count" "$d" "$p" "$d" "$p" "$pcount"
    )
    checkCount "$d/$p" "$count" 1
  done < <(cut -d '>' -f 2 index.html | cut -d '<' -f 1 | grep -ve '^\s*$' || true)
  echo
  cd "$dir"
}

updateHumanIndexes() {
  cat <<'EOF' > whl/index.html
<!DOCTYPE html>
<html>
  <body>
    <h1>Sonatype <a href="https://pytorch.org/">PyTorch</a> PyPI improved indexes for <a href="https://help.sonatype.com/en/pypi-repositories.html#download--search--and-install-packages-using-pip">Nexus Repository</a></h1>

Generated by <a href="https://github.com/sonatype-nexus-community/pytorch-pypi">sonatype-nexus-community/pytorch-pypi</a> from <a href="https://download.pytorch.org/whl/">https://download.pytorch.org/whl/</a>
<p>
for the full index, use <code>--index-url <a href="simple">https://sonatype-nexus-community.github.io/pytorch-pypi/whl/simple</a></code>
<p>
You can also use compute platform filtered indexes:
<ul>
EOF
  local d esc
  for d in whl/*; do
    d="${d#whl/}"
    [ -d "whl/$d" ] || continue
    [ "$d" = "simple" ] && continue
    is_safe_name "$d" || continue
    esc="$(printf '%s' "$d" | html_escape)"
    printf '<li><a href="%s">%s</a></li>\n' "$esc" "$esc" >> whl/index.html
  done
  cat <<'EOF' >> whl/index.html
</ul>
</body>
</html>
EOF

  for d in whl/*; do
    d="${d#whl/}"
    [ -d "whl/$d" ] || continue
    [ "$d" = "simple" ] && continue
    is_safe_name "$d" || continue
    esc="$(printf '%s' "$d" | html_escape)"
    cat > "whl/$d/index.html" <<EOF
<!DOCTYPE html>
<html>
  <body>
    <h1>Sonatype <a href="https://pytorch.org/">PyTorch</a> PyPI improved indexes for <a href="https://help.sonatype.com/en/pypi-repositories.html#download--search--and-install-packages-using-pip">Nexus Repository</a></h1>

Generated by <a href="https://github.com/sonatype-nexus-community/pytorch-pypi">sonatype-nexus-community/pytorch-pypi</a> from <a href="https://download.pytorch.org/whl/${esc}/">https://download.pytorch.org/whl/${esc}/</a>
<p>
for ${esc} compute platform index, use <code>--index-url <a href="simple">https://sonatype-nexus-community.github.io/pytorch-pypi/whl/${esc}/simple</a></code>
<p>
see also <a href="..">other available indexes</a>
</body>
</html>
EOF
  done
}

# update main PyTorch index, that contains everything, whatever the compute platform
updateIndex "whl"
updateIndex "whl/nightly"

# see resulting updates
git update-index -q --refresh
git diff-index --name-status HEAD || true

if git diff-index --quiet HEAD; then
  echo "no update found in PyTorch main index."
  updateHumanIndexes
  exit 0
fi
echo "updates found in PyTorch main index: updating also compute platform specific ones..."

# update compute-platform specific indexes
# To add a new variant, append it to the array below.
# Retired variants (kept here for history):
# - cu75 cu80 cu90 cu91 cu92 cu100 cu101 cu102 cu110 cu111 cu113 cu115 cu116 cu117 cu117_pypi_cudnn
# - rocm3.10 rocm3.7 rocm3.8 rocm4.0.1 rocm4.1 rocm4.2 rocm4.3.1 rocm4.5.2 rocm5.0 rocm5.1.1 rocm5.2 rocm5.3 rocm5.4.2 rocm5.5 rocm5.6 rocm5.7
VARIANTS=(cpu cpu-cxx11-abi cpu_pypi_pkg cu118 cu121 cu124 cu126 cu128 cu129 cu130 rocm6.0 rocm6.1 rocm6.2 rocm6.2.4 rocm6.3 rocm6.4 xpu)
for d in "${VARIANTS[@]}"; do
  updateIndex "whl/$d"
done
updateHumanIndexes

du -sh whl/*

: > summary.txt
for d in whl/simple whl/*/simple; do
  [ -d "$d" ] || continue
  printf '%d %s\n' "$(find "$d" -mindepth 1 -maxdepth 1 | wc -l | tr -d ' ')" "$d" >> summary.txt
done
cat summary.txt
